const express = require('express');
const dashboardRoutes = require('./dashboardRoutes');
const usersRoutes = require('./usersRoutes');
const productsRoutes = require('./productsRoutes');
const ordersRoutes = require('./ordersRoutes');
const walletRoutes = require('./walletRoutes');
const compensationRoutes = require('./compensationRoutes');
const rewardsRoutes = require('./rewardsRoutes');
const teamRoutes = require('./teamRoutes');
const settingsRoutes = require('./settingsRoutes');
const sellerApplicationsRoutes = require('./sellerApplicationsRoutes');
const ranksRoutes = require('./ranksRoutes');
const bannersRoutes = require('./bannersRoutes');
const auctionsRoutes = require('./auctionsRoutes');
const landingRoutes = require('./landingRoutes');
const galleryRoutes = require('./galleryRoutes');
const supportRoutes = require('./supportRoutes');
const helpingHandRoutes = require('./helpingHandRoutes');
const donationsRoutes = require('./donationsRoutes');
const depositsRoutes = require('./depositsRoutes');
const transferRoutes = require('./transferRoutes');

const router = express.Router();

router.use('/dashboard', dashboardRoutes);
router.use('/users', usersRoutes);
router.use('/products', productsRoutes);
router.use('/orders', ordersRoutes);
router.use('/wallet', walletRoutes);
router.use('/wallets', walletRoutes);
router.use('/deposits', depositsRoutes);
router.use('/transfer', transferRoutes);
router.use('/compensation', compensationRoutes);
router.use('/rewards', rewardsRoutes);
router.use('/team', teamRoutes);
router.use('/settings', settingsRoutes);
router.use('/seller-applications', sellerApplicationsRoutes);
router.use('/ranks', ranksRoutes);
router.use('/banners', bannersRoutes);
router.use('/auctions', auctionsRoutes);
router.use('/landing', landingRoutes);
router.use('/gallery', galleryRoutes);
router.use('/support', supportRoutes);
router.use('/helping-hand', helpingHandRoutes);
router.use('/donations', donationsRoutes);

module.exports = router;
