export const COUNTRY_CODE_OPTIONS = [
  { label: 'India (+91)', value: '+91' },
  { label: 'United States (+1)', value: '+1' },
  { label: 'United Kingdom (+44)', value: '+44' },
  { label: 'Canada (+1)', value: '+1' },
  { label: 'Australia (+61)', value: '+61' },
  { label: 'UAE (+971)', value: '+971' },
  { label: 'Saudi Arabia (+966)', value: '+966' },
  { label: 'Qatar (+974)', value: '+974' },
  { label: 'Kuwait (+965)', value: '+965' },
  { label: 'Oman (+968)', value: '+968' },
  { label: 'Bahrain (+973)', value: '+973' },
  { label: 'Singapore (+65)', value: '+65' },
  { label: 'Malaysia (+60)', value: '+60' },
  { label: 'Thailand (+66)', value: '+66' },
  { label: 'Indonesia (+62)', value: '+62' },
  { label: 'Philippines (+63)', value: '+63' },
  { label: 'Bangladesh (+880)', value: '+880' },
  { label: 'Pakistan (+92)', value: '+92' },
  { label: 'Nepal (+977)', value: '+977' },
  { label: 'Sri Lanka (+94)', value: '+94' },
  { label: 'Japan (+81)', value: '+81' },
  { label: 'South Korea (+82)', value: '+82' },
  { label: 'China (+86)', value: '+86' },
  { label: 'Germany (+49)', value: '+49' },
  { label: 'France (+33)', value: '+33' },
  { label: 'Italy (+39)', value: '+39' },
  { label: 'Spain (+34)', value: '+34' },
  { label: 'Netherlands (+31)', value: '+31' },
  { label: 'Belgium (+32)', value: '+32' },
  { label: 'Switzerland (+41)', value: '+41' },
  { label: 'Austria (+43)', value: '+43' },
  { label: 'Sweden (+46)', value: '+46' },
  { label: 'Norway (+47)', value: '+47' },
  { label: 'Denmark (+45)', value: '+45' },
  { label: 'Poland (+48)', value: '+48' },
  { label: 'Portugal (+351)', value: '+351' },
  { label: 'Ireland (+353)', value: '+353' },
  { label: 'Turkey (+90)', value: '+90' },
  { label: 'South Africa (+27)', value: '+27' },
  { label: 'Nigeria (+234)', value: '+234' },
  { label: 'Kenya (+254)', value: '+254' },
  { label: 'Egypt (+20)', value: '+20' },
  { label: 'Brazil (+55)', value: '+55' },
  { label: 'Argentina (+54)', value: '+54' },
  { label: 'Mexico (+52)', value: '+52' },
  { label: 'Colombia (+57)', value: '+57' },
  { label: 'Peru (+51)', value: '+51' },
  { label: 'Chile (+56)', value: '+56' },
  { label: 'Custom (enter manually)', value: 'custom' }
];
