export const queryKeys = {
  me: ['me'],
  sellerMe: ['seller', 'me'],
  sellerProducts: ['seller', 'products'],
  wallet: ['wallet'],
  walletTransactions: ['wallet', 'transactions'],
  walletDeposits: ['wallet', 'deposits'],
  walletWithdrawals: ['wallet', 'withdrawals'],
  walletP2p: ['wallet', 'p2p'],
  walletHubHistory: (type = 'all') => ['wallet', 'history', type],
  products: ['products'],
  orders: ['orders'],
  homepageBanners: ['homepage-banners'],
  admin: ['admin'],
  adminDashboard: ['admin', 'dashboard'],
  adminUsers: ['admin', 'users'],
  adminUsersSearch: (q, page = 1, limit = 10) => ['admin', 'users', 'search', q, page, limit],
  adminUserDetail: (id) => ['admin', 'users', id],
  adminUserFinancialOverview: (id) => ['admin', 'users', id, 'financial-overview'],
  adminRanks: ['admin', 'ranks'],
  adminProducts: ['admin', 'products'],
  adminBanners: ['admin', 'banners'],
  adminProductDetail: (id) => ['admin', 'products', id],
  adminOrders: ['admin', 'orders'],
  adminOrderDetail: (id) => ['admin', 'orders', id],
  adminWallet: ['admin', 'wallet'],
  adminWalletSummary: ['admin', 'wallet', 'summary'],
  adminWalletTransactions: ['admin', 'wallet', 'transactions'],
  adminDeposits: ['admin', 'deposits'],
  adminWithdrawals: ['admin', 'withdrawals'],
  adminP2p: ['admin', 'p2p'],
  adminWalletBindings: ['admin', 'wallet-bindings'],
  adminIncome: ['admin', 'income'],
  adminCompensation: ['admin', 'compensation'],
  adminCompensationWeekly: ['admin', 'compensation', 'weekly'],
  adminCompensationMonthly: ['admin', 'compensation', 'monthly'],
  adminCompensationWeeklyDetail: (id) => ['admin', 'compensation', 'weekly', id],
  adminCompensationMonthlyDetail: (id) => ['admin', 'compensation', 'monthly', id],
  adminRewards: ['admin', 'rewards'],
  adminRewardsSummary: ['admin', 'rewards', 'summary'],
  adminTeam: ['admin', 'team'],
  adminTeamSummary: (id) => ['admin', 'team', 'summary', id],
  adminTeamTree: (id, depth) => ['admin', 'team', 'tree', id, depth],
  adminSettings: ['admin', 'settings'],
  weeklyCompensationRoot: ['weekly-compensation'],
  monthlyCompensationRoot: ['monthly-compensation'],
  weeklyCompensation: (cycleStart, cycleEnd) => ['weekly-compensation', cycleStart, cycleEnd],
  monthlyCompensation: (monthStart, monthEnd) => ['monthly-compensation', monthStart, monthEnd],
  teamChildren: ['team-children']
};
