export const queryKeys = {
  me: ['me'],
  webauthn: ['me', 'webauthn'],
  welcomeSpinStatus: ['me', 'welcome-spin', 'status'],
  userAddress: ['user-address'],
  sellerMe: ['seller', 'me'],
  sellerAccess: ['seller', 'access'],
  sellerProducts: ['seller', 'products'],
  wallet: ['wallet'],
  walletTransactions: ['wallet', 'transactions'],
  walletDepositConfig: ['wallet', 'deposit-config'],
  walletDeposits: ['wallet', 'deposits'],
  walletWithdrawals: ['wallet', 'withdrawals'],
  walletP2p: ['wallet', 'p2p'],
  walletStaking: ['wallet', 'staking'],
  walletHubHistory: (type = 'all') => ['wallet', 'history', type],
  products: ['products'],
  productDetail: (id) => ['products', id],
  auctions: ['auctions'],
  auctionDetail: (id) => ['auctions', id],
  auctionHistory: (kind = 'bids') => ['auctions', 'history', kind],
  orders: ['orders'],
  homeProducts: ['products', 'home'],
  notificationsRoot: ['notifications'],
  notifications: (page = 1) => ['notifications', page],
  notificationsUnreadCount: ['notifications', 'unread-count'],
  paymentDetail: (id) => ['payments', id],
  supportThreads: ['support', 'threads'],
  supportThreadDetail: (id) => ['support', 'threads', id],
  homepageBanners: ['homepage-banners'],
  admin: ['admin'],
  adminDashboard: ['admin', 'dashboard'],
  adminUsers: ['admin', 'users'],
  adminUsersSearch: (q, page = 1, limit = 10) => ['admin', 'users', 'search', q, page, limit],
  adminUserDetail: (id) => ['admin', 'users', id],
  adminUserFinancialOverview: (id) => ['admin', 'users', id, 'financial-overview'],
  adminRanks: ['admin', 'ranks'],
  adminProducts: ['admin', 'products'],
  adminBanners: ['admin', 'banners'],
  adminProductDetail: (id) => ['admin', 'products', id],
  adminAuctions: ['admin', 'auctions'],
  adminAuctionDetail: (id) => ['admin', 'auctions', id],
  adminOrders: ['admin', 'orders'],
  adminOrderDetail: (id) => ['admin', 'orders', id],
  adminWallet: ['admin', 'wallet'],
  adminWalletSummary: ['admin', 'wallet', 'summary'],
  adminWalletTransactions: ['admin', 'wallet', 'transactions'],
  adminWalletUsers: ['admin', 'wallet', 'users'],
  adminWalletUser: (id) => ['admin', 'wallet', 'users', id],
  adminWalletLogs: ['admin', 'wallet', 'logs'],
  adminDeposits: ['admin', 'deposits'],
  adminNowPayments: ['admin', 'nowpayments'],
  adminWithdrawals: ['admin', 'withdrawals'],
  adminP2p: ['admin', 'p2p'],
  adminWalletBindings: ['admin', 'wallet-bindings'],
  adminIncome: ['admin', 'income'],
  adminBtctStaking: ['admin', 'btct-staking'],
  adminCompensation: ['admin', 'compensation'],
  adminCompensationWeekly: ['admin', 'compensation', 'weekly'],
  adminCompensationMonthly: ['admin', 'compensation', 'monthly'],
  adminCompensationWeeklyDetail: (id) => ['admin', 'compensation', 'weekly', id],
  adminCompensationMonthlyDetail: (id) => ['admin', 'compensation', 'monthly', id],
  adminRewards: ['admin', 'rewards'],
  adminRewardsSummary: ['admin', 'rewards', 'summary'],
  adminTeam: ['admin', 'team'],
  adminTeamSummary: (id) => ['admin', 'team', 'summary', id],
  adminTeamTree: (id, depth) => ['admin', 'team', 'tree', id, depth],
  adminSettings: ['admin', 'settings'],
  adminDepositWalletSettings: ['admin', 'settings', 'deposit-wallet'],
  weeklyCompensationRoot: ['weekly-compensation'],
  monthlyCompensationRoot: ['monthly-compensation'],
  weeklyCompensation: (cycleStart, cycleEnd) => ['weekly-compensation', cycleStart, cycleEnd],
  monthlyCompensation: (monthStart, monthEnd) => ['monthly-compensation', monthStart, monthEnd],
  teamChildren: ['team-children'],
  teamSummary: ['team-summary'],
  teamTreeRoot: ['team-tree', 'root'],
  teamTreeNode: (id) => ['team-tree', id],
  landingPage: ['landing-page'],
  publicGallery: ['public-gallery'],
  adminLanding: ['admin', 'landing'],
  adminGallery: ['admin', 'gallery'],
  adminSupport: ['admin', 'support'],
  adminSupportDetail: (id) => ['admin', 'support', id]
};



